sudo: false
language: ruby
cache: bundler

bundler_args: --jobs 7

before_install:
  - gem update --system
  - gem install bundler

matrix:
  include:
    - rvm: 2.1.9
    - rvm: 2.2.5
    - rvm: 2.3.1
  allow_failures:
    - rvm: 2.3.1

script: bundle exec rake travis:ci
